import type { RepoFacts } from "./facts.js";
import type { ReggieConfig } from "./people.js";
import { readText, today, writeText } from "./util.js";

export const START_MARKER = "<!-- reggie:generated:start -->";
export const END_MARKER = "<!-- reggie:generated:end -->";

export type Tool = "claude" | "codex";

/** The block Reggie owns inside CLAUDE.md and AGENTS.md. Kept short on purpose: it is loaded into every session. */
export function renderGeneratedBlock(facts: RepoFacts, config: ReggieConfig, tool: Tool): string {
  const langs = facts.languages.slice(0, 5).map((l) => `${l.language} ${l.files}`).join(", ") || "none detected";
  const top = facts.topLevel
    .filter((d) => d.dir !== "(root)")
    .slice(0, 10)
    .map((d) => `\`${d.dir}\` ${d.files}`)
    .join(", ");
  const commands = facts.commands.length > 0 ? facts.commands.map((c) => `- ${c.label}: \`${c.command}\``).join("\n") : "- none detected; see the curated section above";
  const entries = facts.entryPoints.length > 0 ? facts.entryPoints.map((e) => `\`${e}\``).join(", ") : "none detected";
  const tests = facts.tests.count > 0 ? `${facts.tests.count} test files under ${facts.tests.dirs.map((d) => `\`${d}\``).join(", ")}` : "no test files detected";
  const ci = facts.ci.length > 0 ? facts.ci.map((c) => `\`${c}\``).join(", ") : "none";
  const toolName = tool === "claude" ? "Claude Code" : "Codex";
  const mcp = tool === "claude"
    ? `The \`${config.mcpServerName}\` MCP server is configured in \`.mcp.json\`. Prefer its tools over re-deriving state.`
    : `Register the MCP server once with \`codex mcp add ${config.mcpServerName} -- reggie mcp\`. Prefer its tools over re-deriving state.`;

  const lines = [
    START_MARKER,
    "<!-- Generated by Reggie. Do not edit inside these markers. Refresh with `reggie docs refresh`. -->",
    `## Repo facts (generated ${today(new Date(facts.generatedAt))})`,
    `- **${facts.name}**${facts.description ? `: ${facts.description}` : ""}`,
    `- Languages: ${langs}. Files: ${facts.totalFiles}.`,
    `- Structure: ${top || "flat"}`,
    `- Manifests: ${facts.manifests.map((m) => `\`${m}\``).join(", ") || "none"}`,
    `- Entry points: ${entries}`,
    `- Tests: ${tests}. CI: ${ci}.`,
    "",
    "## Commands (generated)",
    commands,
    "",
    "## Where information lives (generated)",
    "- Before editing a file, read its note at `.reggie/notes/<same path>.md`. Folder notes are `_dir.md`; repo-wide notes are `.reggie/notes/_repo.md`.",
    "- After changing a file, add or correct its note: `reggie note add <path> --type <why|how|gotcha|verify|data-source|decision> \"text\"`.",
    "- Before starting a task, run `reggie context <slug>` (or `reggie context <path...>`). It gathers the notes, related tasks, recent commits, and active work for that area.",
    "- Plans live at `.reggie/tasks/<slug>/plan.md` and must satisfy the plan contract (`reggie plan lint <slug>`). Completion packets live beside them as `packet.md`, with proof under `evidence/`.",
    "- After each step of work, write one plain-English journal entry: `reggie journal add --slug <slug> --stage <stage> \"what happened, why, what is uncertain\"`. No file paths in the prose.",
    "- Raw ideas and discovered issues go to `.reggie/intake.md` via `reggie capture \"text\"`. Never fix unrelated issues in passing; capture them.",
    "",
    `## Working here with Reggie and ${toolName} (generated)`,
    `- Mode: **${config.mode}**. Task state is read from git: intake line = ungroomed, plan merged = groomed, \`task/<slug>\` branch = in process, open PR = awaiting decision, merged = done.`,
    "- Plan in plan mode against the contract, then `reggie claim <slug>` to start work on a `task/<slug>` branch. Finish with `reggie packet <slug>` and a PR whose body is the packet.",
    `- ${mcp}`,
    END_MARKER,
  ];
  return lines.join("\n");
}

export interface ApplyResult {
  file: string;
  action: "created" | "updated" | "unchanged";
}

/** Insert or replace the generated block. Creates the file from a template when missing. */
export function applyGeneratedBlock(file: string, block: string, template: (block: string) => string): ApplyResult {
  const existing = readText(file);
  if (existing === null) {
    writeText(file, template(block));
    return { file, action: "created" };
  }
  const next = replaceBlock(existing, block);
  if (next === existing) return { file, action: "unchanged" };
  writeText(file, next);
  return { file, action: "updated" };
}

/** The real block is the LAST start marker that begins a line and its following end marker; prose may quote the markers above it. */
function locateBlock(content: string): { start: number; end: number } | null {
  const re = new RegExp(`^${START_MARKER.replace(/[-/\\^$*+?.()|[\]{}]/g, "\\$&")}\\s*$`, "gm");
  let start = -1;
  for (const m of content.matchAll(re)) start = m.index;
  if (start === -1) return null;
  const end = content.indexOf(END_MARKER, start);
  if (end === -1) return null;
  return { start, end: end + END_MARKER.length };
}

export function replaceBlock(content: string, block: string): string {
  const loc = locateBlock(content);
  if (loc) return content.slice(0, loc.start) + block + content.slice(loc.end);
  const sep = content.endsWith("\n") ? "\n" : "\n\n";
  return `${content}${sep}${block}\n`;
}

/** Compare the generated block on disk to a fresh one. Ignores the generation date line. */
export function checkGeneratedBlock(file: string, block: string): { file: string; status: "missing" | "stale" | "fresh" } {
  const existing = readText(file);
  if (existing === null) return { file, status: "missing" };
  const loc = locateBlock(existing);
  if (!loc) return { file, status: "missing" };
  const current = normalizeBlock(existing.slice(loc.start, loc.end));
  return { file, status: current === normalizeBlock(block) ? "fresh" : "stale" };
}

function normalizeBlock(block: string): string {
  return block.replace(/\(generated \d{4}-\d{2}-\d{2}\)/g, "(generated)").trim();
}

export function claudeMdTemplate(name: string): (block: string) => string {
  return (block) =>
    [
      `# ${name}`,
      "",
      "Curated notes for anyone, human or agent, working in this repo. Edit freely outside the generated block.",
      "",
      "## Conventions",
      "- (add the rules a new teammate would need on day one)",
      "",
      "## Decisions",
      "- (record choices and the alternatives that were rejected; link to `.reggie/notes/` entries)",
      "",
      "## Gotchas",
      "- (what will bite you)",
      "",
      block,
      "",
    ].join("\n");
}

export function agentsMdTemplate(name: string): (block: string) => string {
  return (block) =>
    [
      `# ${name} — instructions for Codex`,
      "",
      "This file mirrors CLAUDE.md for Codex. Curated sections are shared by convention; the generated block is identical in both files.",
      "",
      "## Conventions",
      "- (keep in sync with CLAUDE.md, or make CLAUDE.md a symlink to this file)",
      "",
      block,
      "",
    ].join("\n");
}
