import { describe, expect, it } from "vitest";
import { ROLES, TEST_HINTS, isTestLike, roleOf, type Role } from "./roles.js";

/** One table per role; every path here must land on its key with no first line given. */
const BY_ROLE: Record<Role, string[]> = {
  source: [
    "src/index.ts",
    "src/components/Sidebar.tsx",
    "packages/reggie/src/facts.ts",
    "src-tauri/src/main.rs",
    "src/config.ts", // no `.config.` segment
    "src/configure.ts",
    "src/testing.ts", // `test` in a name is not a test hint
    "cmd/app/main.go",
    "Sources/App/App.swift",
    "app/src/main/Foo.kt",
    "src/models.py",
    "lib/helpers.ts", // helpers outside a test directory
    "src/distribution/report.ts", // `dist` only as a full segment
    "src/gen/schema.ts", // `.gen.` only in the basename
    "ui/app.js",
  ],
  test: [
    "src/roles.test.ts",
    "src/facts.spec.tsx",
    "src/store.test.mjs",
    "test/mcp.test.ts",
    "tests/integration/run.ts",
    "test/fixtures.ts", // a file named fixtures, not a fixtures directory
    "test/helpers.test.ts", // a test of the helpers, not the helpers
    "src/__tests__/graph.ts",
    "__tests__/root.ts",
    "pkg/git/clone_test.go",
    "Tests/AppTests/LoginTests.swift",
    "Tests/AppTests/LoginTest.swift",
    "app/src/test/LoginTest.kt",
    "tests/test_login.py",
    "app/login_test.py",
    "src/app.config.test.ts", // a test beats a config-looking basename
    "test/setup.ts",
    "tests/tsconfig.json", // a config basename inside a test tree: the directory hint wins (see roles.ts precedence)
  ],
  fixture: [
    "test/helpers.ts",
    "tests/helpers.py",
    "packages/reggie/test/helpers.ts",
    "src/__tests__/helpers.ts",
    "src/__mocks__/fs.ts",
    "__mocks__/node-fetch.js",
    "test/fixtures/repo.json",
    "fixtures/graph.ts",
    "src/__test-utils__/render.tsx",
    "src/__tests__/__mocks__/api.ts", // fixture beats the test directory it sits in
    "test/fixtures/sample.test.ts", // fixture beats the .test suffix
  ],
  config: [
    "vite.config.ts",
    "vitest.config.ts",
    "packages/reggie/vitest.config.ts",
    "tailwind.config.js",
    "eslint.config.mjs",
    "jest.config.cjs",
    "tsconfig.json",
    "tsconfig.node.json",
    "packages/reggie/tsconfig.build.json",
    "src-tauri/build.rs",
    "build.rs",
    "src/vite-env.d.ts",
    "src/types/global.d.ts",
    "src/types/env.d.mts",
  ],
  generated: [
    "dist/cli.js",
    "packages/reggie/dist/index.js",
    "dist/cli.test.js", // build output beats the test suffix
    "src/routeTree.gen.ts",
    "src/api/schema.gen.go",
    "src/api/client.gen.d.ts", // codegen beats the declaration-file rule
  ],
};

describe("roleOf", () => {
  for (const role of ROLES) {
    it(`classifies ${role} paths`, () => {
      for (const p of BY_ROLE[role]) expect(roleOf(p), p).toBe(role);
    });
  }

  it("covers every role in the table", () => {
    expect(Object.keys(BY_ROLE).sort()).toEqual([...ROLES].sort());
    expect(new Set(ROLES).size).toBe(5);
  });

  describe("first-line generated markers", () => {
    it("recognises @generated and DO NOT EDIT", () => {
      expect(roleOf("src/api.ts", "// @generated by openapi-typescript")).toBe("generated");
      expect(roleOf("src/api.ts", "/* eslint-disable */ // DO NOT EDIT")).toBe("generated");
      expect(roleOf("src/api.ts", "# Do not edit: regenerate with `make gen`")).toBe("generated");
    });

    it("treats an ordinary or missing first line as source", () => {
      expect(roleOf("src/api.ts", 'import x from "y";')).toBe("source");
      expect(roleOf("src/api.ts", "")).toBe("source");
      expect(roleOf("src/api.ts", undefined)).toBe("source");
      expect(roleOf("src/api.ts")).toBe("source");
    });

    it("only reads the first line of whatever it is handed", () => {
      expect(roleOf("src/api.ts", "// @generated\nexport {};\n")).toBe("generated");
      expect(roleOf("src/api.ts", "export {};\n// @generated\n")).toBe("source");
      expect(roleOf("src/api.ts", "// @generated\r\nexport {};\r\n")).toBe("generated");
    });

    it("beats every path rule", () => {
      expect(roleOf("src/api.test.ts", "// @generated")).toBe("generated");
      expect(roleOf("test/helpers.ts", "// @generated")).toBe("generated");
      expect(roleOf("src/vite-env.d.ts", "// DO NOT EDIT")).toBe("generated");
    });
  });

  describe("precedence", () => {
    it("fixture beats test", () => {
      expect(roleOf("test/helpers.ts")).toBe("fixture");
      expect(roleOf("src/__tests__/__mocks__/api.ts")).toBe("fixture");
    });
    it("test beats config", () => {
      expect(roleOf("src/app.config.test.ts")).toBe("test");
      expect(roleOf("src/app.config.spec.ts")).toBe("test");
    });
    it("generated beats everything", () => {
      expect(roleOf("dist/__tests__/x.test.ts")).toBe("generated");
      expect(roleOf("dist/tsconfig.json")).toBe("generated");
      expect(roleOf("test/fixtures/schema.gen.ts")).toBe("generated");
    });
  });

  it("tolerates a leading ./ and backslashes", () => {
    expect(roleOf("./src/index.ts")).toBe("source");
    expect(roleOf("./test/helpers.ts")).toBe("fixture");
    expect(roleOf("src\\roles.test.ts")).toBe("test");
    expect(roleOf("src\\vite-env.d.ts")).toBe("config");
  });

  it("returns only contract roles", () => {
    for (const paths of Object.values(BY_ROLE)) for (const p of paths) expect(ROLES).toContain(roleOf(p));
  });
});

describe("TEST_HINTS", () => {
  it("is exported for facts.ts and matches the classic shapes", () => {
    const hit = (p: string) => TEST_HINTS.some((re) => re.test(p));
    expect(hit("src/x.test.ts")).toBe(true);
    expect(hit("src/x.spec.jsx")).toBe(true);
    expect(hit("tests/x.ts")).toBe(true);
    expect(hit("__tests__/x.ts")).toBe(true);
    expect(hit("a_test.go")).toBe(true);
    expect(hit("src/x.ts")).toBe(false);
  });

  it("carries no global flags, so repeated test() calls stay stateless", () => {
    for (const re of TEST_HINTS) expect(re.global, re.source).toBe(false);
    for (let i = 0; i < 3; i += 1) expect(TEST_HINTS.some((re) => re.test("src/x.test.ts"))).toBe(true);
  });
});

describe("isTestLike", () => {
  it("is true for test and fixture only", () => {
    expect(isTestLike("test")).toBe(true);
    expect(isTestLike("fixture")).toBe(true);
    expect(isTestLike("source")).toBe(false);
    expect(isTestLike("config")).toBe(false);
    expect(isTestLike("generated")).toBe(false);
  });
});
